name: get_10101
description: 10101 combines the power of a self-custodial on-chain and off-chain wallet with the vast world of trading.
publish_to: none
version: 1.8.6
environment:
  sdk: '>=3.1.2 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  google_fonts: ^6.1.0
  ffi: ^2.0.2
  flutter_rust_bridge: ^1.78.0
  bitcoin_icons: ^0.0.4
  meta: ^1.8.0
  go_router: ^9.0.0
  flutter_native_splash: ^2.2.19
  flutter_svg: ^2.0.5
  provider: ^6.0.5
  intl: ^0.18.0
  decimal: ^2.3.2
  slide_to_confirm: ^1.1.0
  path_provider: ^2.0.15
  freezed_annotation: ^2.2.0
  font_awesome_flutter: 10.6.0
  expandable: ^5.0.1
  qr_flutter: ^4.0.0
  share_plus: ^7.0.2
  logger: ^2.0.2+1
  carousel_slider: ^4.2.1
  candlesticks: ^2.1.0
  http: ^1.0.0
  timeago: ^3.3.0
  shared_preferences: ^2.1.2
  package_info_plus: ^4.0.2
  uuid: ^3.0.7
  confetti: ^0.7.0
  social_share: ^2.3.1
  test: ^1.24.1
  version: ^3.0.2
  firebase_core: ^2.15.0
  firebase_messaging: ^14.6.5
  flutter_local_notifications: ^15.1.0+1
  url_launcher: ^6.1.14
  nested: ^1.0.0
  qr_code_scanner: ^1.0.1
  fl_chart: 0.64.0
dependency_overrides:
  intl: ^0.18.0
dev_dependencies:
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.2
  ffigen: ^8.0.0
  freezed: ^2.3.5
  build_runner: ^2.3.3
  mockito: ^5.4.0
flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: SendReceiveIcons
      fonts:
        - asset: fonts/SendReceiveIcons.ttf
    - family: CustomIcon
      fonts:
        - asset: assets/fonts/CustomIcon.ttf
flutter_native_splash:
  color: '#FFFFFF'
  image: assets/LaunchImage.png
  android_12: null
flutter_icons:
  android: true
  ios: true
  image_path: assets/10101_logo_icon.png
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: false
  macos:
    generate: true
    image_path: assets/10101_logo_icon.png
  windows:
    generate: true
    image_path: assets/10101_logo_icon.png
