name: get_10101
description: 10101 combines the power of a self-custodial on-chain and off-chain wallet with the vast world of trading.

publish_to: "none" # Remove this line if you wish to publish to pub.dev
version: 1.0.2
environment:
  sdk: ">=2.17.5 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.5
  ffi: ^2.0.1
  f_logs: ^2.0.1
  flutter_rust_bridge: 1.68.0
  flutter_speed_dial: ^6.2.0
  meta: ^1.8.0
  go_router: ^6.0.2
  flutter_native_splash: ^2.2.16
  flutter_svg: ^2.0.0+1
  provider: ^6.0.5
  intl: ^0.17.0
  decimal: ^2.3.2
  slide_to_confirm: ^1.1.0
  path_provider: ^2.0.11
  freezed_annotation: ^2.2.0
  expandable: ^5.0.1
  qr_flutter: ^4.0.0
  share_plus: ^6.3.1
  candlesticks: ^2.1.0
  http: ^0.13.5
  timeago: ^3.3.0

dev_dependencies:
  flutter_launcher_icons: "^0.13.0"
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.1
  ffigen: ^7.2.4
  freezed: ^2.2.1
  build_runner: ^2.2.0
  mockito: ^5.3.2

flutter:
  uses-material-design: true
  assets:
    - assets/
  fonts:
    - family: SendReceiveIcons
      fonts:
        - asset: fonts/SendReceiveIcons.ttf

flutter_native_splash:
  color: "#FFFFFF"
  image: assets/10101.finance_logo_1500x1500.png
  android_12: null

flutter_icons:
  android: true
  ios: true
  image_path: assets/10101_logo_icon.png
  min_sdk_android: 21
  remove_alpha_ios: true
  web:
    generate: false
  macos:
    generate: true
    image_path: assets/10101_logo_icon.png
  windows:
    generate: true
    image_path: assets/10101_logo_icon.png
