jit_channels_enabled = true
new_positions_enabled = true
contract_tx_fee_rate = 9
fallback_tx_fee_rate_normal = 2000
fallback_tx_fee_rate_high_priority = 5000
rollover_window_open_scheduler = "0 5 15 * * 5,6"
rollover_window_close_scheduler = "0 5 13 * * 5,6"
close_expired_position_scheduler = "0 0 12 * * *"
min_liquidity_threshold_sats = 10000000
whitelist_enabled = false
whitelisted_makers = []

[ln_dlc]
off_chain_sync_interval = 5
on_chain_sync_interval = 300
fee_rate_sync_interval = 20
dlc_manager_periodic_check_interval = 30
sub_channel_manager_periodic_check_interval = 30
shadow_sync_interval = 600
forwarding_fee_proportional_millionths = 1000
bdk_client_stop_gap = 20
bdk_client_concurrency = 4

[ln_dlc.gossip_source_config.RapidGossipSync]
server_url = "https://rapidsync.lightningdevkit.org/snapshot/"
