new_positions_enabled = true
contract_tx_fee_rate = 9
rollover_window_open_scheduler = "0 5 16 * * *"
rollover_window_close_scheduler = "0 5 22 * * *"
close_expired_position_scheduler = "0 0 12 * * *"
close_liquidated_position_scheduler = "0 0 12 * * *"
update_user_bonus_status_scheduler = "0 0 0 * * *"
whitelist_enabled = false
# Default testnet maker
whitelisted_makers = ["035eccdd1f05c65b433cf38e3b2597e33715e0392cb14d183e812f1319eb7b6794"]
min_quantity = 1
maintenance_margin_rate = 0.1
order_matching_fee_rate = 0.003

[ln_dlc]
off_chain_sync_interval = 5
on_chain_sync_interval = 300
fee_rate_sync_interval = 20
sub_channel_manager_periodic_check_interval = 30
shadow_sync_interval = 600
